### PR TITLE
Replaces the 'dd' prefix with the DynamicData property 'PropertyPrefix'.

### PR DESCRIPTION
**Pull request by sphh**
As discussed in #73.

I split it into smaller commits…

I have two questions as mentioned in https://github.com/mwganson/DynamicData/commit/44577ea5646980f49b4b41f15f52e225a1078b12:
1. The original code not only checks for 'dd', but also for 'Dd'. This check has been removed. Is this still needed? (And why?)
2. The original code checks for CamelCase of property names. This check remains, but is this still needed? (And why?)

I also took the liberty to make some other mostly cosmetic changes.

### CODE REVIEW

**Comment by sphh** [comment]
BTW I could only test the most basic features, because I never used the other features. I would appreciate if you could test them, because you know exactly how they should work. Thanks.

**Comment by mwganson** [comment]
Some of these would be accepted as separate PR's, such as the message changes, updating to python 3 syntax, removing whitespace.  I don't want to add another property to the dd object or have the preference to keep the prefix, anymore.  I just tested 0.21, and it also does not benefit from the dd prefix the way earlier versions did.  I have a method in one of the commands to check if a property is a dynamic property that does not involve looking for the dd prefix.

**Comment by sphh** [comment]
Ok, I see. I tried to
1. Keep backward compatibility
   1. with old files
   2. with old versions of FreeCAD 
3. Give the users the chance to keep their preferences, so that they don't need to change their way of working (but can, if they want to update it)

I cannot follow your arguments (e.g. why is an additional property bad, if you already have added a `DynamicData` property?). Also reading through your replies to a couple of issues, I get the impression, that you change your mind often. I should have seen that coming. My fault. Obviously it is entirely up to you, how you want to proceed, but I would prefer if you do not use my PR at all. Thanks.

**Comment by mwganson** [comment]
I apologize for changing my mind.  It happens sometimes.  Thank you for your contribution.  You have given me some good ideas for moving forward.

**Comment by sphh** [comment]
I get the feeling, that you got the wrong end of the stick. The problem is absolutely not, that you changed your mind – software development is an ongoing thing. I see the problem, that you take away the choice from the user and decide what is best for him/her instead of giving him/her the choice. But that might be just my opinion …

**Pull request closed without merging**
